[data]

#[data.rawdata]
#type = "raw"
#source = "data"
#
#[data.eddf]
#type = "aixm"
#source = "aixm/EDDF_AerodromeMapping_2024-10-31_2024-10-31_snapshot.xml"
#
#[data.eddf_layout]
#type = "kml"
#source = "kml/EDDF/layout.kml"
#
#[data.eddf_notam]
#type = "kml"
#source = "kml/EDDF/notam.kml"
#
#data.eddl]
#ype = "aixm"
#ource = "aixm/EDDL_AerodromeMapping_2024-06-13_2024-06-13_snapshot.xml"
#
#data.eddl_layout]
#ype = "kml"
#ource = "kml/EDDL/layout.kml"
#
#data.eddl_notam]
#ype = "kml"
#ource = "kml/EDDL/notam.kml"
#
[data.eddk]
type = "aixm"
source = "aixm/EDDK_AerodromeMapping_2024-09-05_2024-09-05_snapshot.xml"

[data.eddk_layout]
type = "kml"
source = "kml/EDDK/layout.kml"
#
[data.edds]
type = "aixm"
source = "aixm/EDDS_AerodromeMapping_2024-11-28_2024-11-28_snapshot.xml"

[data.edds_layout]
type = "kml"
source = "kml/EDDS/layout.kml"
#
#[data.eddg_layout]
#type = "kml"
#source = "kml/EDDG/layout.kml"
#
#[data.eddr]
#type = "aixm"
#source = "aixm/EDDR_AerodromeMapping_2024-07-11_2024-07-11_snapshot.xml"
#
#[data.eddr_layout]
#type = "kml"
#source = "kml/EDDR/layout.kml"
#
#[data.edlp]
#type = "aixm"
#source = "aixm/EDLP_AerodromeMapping_2024-05-16_2024-05-16_snapshot.xml"
#
#[data.edlp_layout]
#type = "kml"
#source = "kml/EDLP/layout.kml"
#
[data.edlw]
type = "aixm"
source = "aixm/EDLW_AerodromeMapping_2024-05-16_2024-05-16_snapshot.xml"

[data.edlw_layout]
type = "kml"
source = "kml/EDLW/layout.kml"
#
#[data.edln]
#type = "aixm"
#source = "aixm/EDLN_AerodromeMapping_2024-06-13_2024-06-13_snapshot.xml"
#
#[data.edln_layout]
#type = "kml"
#source = "kml/EDLN/layout.kml"
#
#[data.edlv]
#type = "aixm"
#source = "aixm/EDLV_AerodromeMapping_2024-06-13_2024-06-13_snapshot.xml"
#
#[data.edlv_layout]
#type = "kml"
#source = "kml/EDLV/layout.kml"
#
#[data.edfh]
#type = "aixm"
#source = "aixm/EDFH_AerodromeMapping_2024-07-11_2024-07-11_snapshot.xml"
#
#[data.edfh_layout]
#type = "kml"
#source = "kml/EDFH/layout.kml"
#
#[data.edfm_layout]
#type = "kml"
#source = "kml/EDFM/layout.kml"
#
#[data.edsb]
#type = "aixm"
#source = "aixm/EDSB_AerodromeMapping_2024-07-11_2024-07-11_snapshot.xml"
#
#[data.edsb_layout]
#type = "kml"
#source = "kml/EDSB/layout.kml"
#
#[data.edtl_layout]
#type = "kml"
#source = "kml/EDTL/layout.kml"



[profiles]

[profiles.Default]
maps = [
#    { map = "EDDF", target = "grp/eddf.txt" },
#    { map = "EDDL", target = "grp/eddl.txt" },
    { map = "EDDK", target = "grp/eddk.txt" },
    { map = "EDDS", target = "grp/edds.txt" },
#    { map = "EDDG", target = "grp/eddg.txt" },
#    { map = "EDDR", target = "grp/eddr.txt" },
#    { map = "EDLP", target = "grp/edlp.txt" },
    { map = "EDLW", target = "grp/edlw.txt" },
#    { map = "EDLN", target = "grp/edln.txt" },
#    { map = "EDLV", target = "grp/edlv.txt" },
#    { map = "EDFH", target = "grp/edfh.txt" },
#    { map = "EDFM", target = "grp/edfm.txt" },
#    { map = "EDSB", target = "grp/edsb.txt" },
#    { map = "EDTL", target = "grp/edtl.txt" },
]
dir = "grp"
aliases = [ "Default" ]

#[profiles.TWR_DAY]
#maps = [
#    { map = "settings-grplugin-phoenix", target = "Plugins/EDWW FIR beta/TWR_DAY/GRpluginSettings.txt" },
#    { map = "settings-topsky-phoenix", target = "Plugins/EDWW FIR beta/TWR_DAY/TopSkySettings.txt" },
#    { map = "grplugin-phoenix", target = "Plugins/EDWW FIR beta/TWR_DAY/GRpluginMaps.txt" },
#    { map = "topsky-phoenix", target = "Plugins/EDWW FIR beta/TWR_DAY/TopSkyMaps.txt" },
#]
#dir = "Plugins/EDWW FIR beta/TWR_DAY/"
#aliases = [ "bright" ]

[runways]

#-----------EDDF--------------

[runways.EDDF.25L]
thr = [ 50.040063, 8.586539 ]
bearing = 249.5
loc = [ 50.026429, 8.529514 ]

[runways.EDDF.07R]
thr = [ 50.027549, 8.534168 ] 
bearing = 69.5
loc = [ 50.041533, 8.592718 ]

[runways.EDDF.25C]
thr = [ 50.045128, 8.586970 ]
bearing = 249.5
loc = [ 50.031371, 8.529415 ]

[runways.EDDF.07C]
thr = [ 50.032623, 8.534621 ] 
bearing = 69.5
loc = [ 50.046411, 8.592353 ]

[runways.EDDF.25R]
thr = [ 50.045830, 8.533712 ]
bearing = 249.5
loc = [ 50.035716, 8.491459 ]

[runways.EDDF.07L]
thr = [ 50.037055, 8.497062 ] 
bearing = 69.5
loc = [ 50.047195, 8.539341 ]

#-----------EDDL--------------

[runways.EDDL.23L]
thr = [ 51.294278, 6.782787 ]
bearing = 233
loc = [ 51.277864, 6.748345 ]

[runways.EDDL.05R]
thr = [ 51.281248, 6.755424 ] 
bearing = 53
loc = [ 51.297669, 6.789874 ]

[runways.EDDL.23R]
thr = [ 51.296757, 6.776128 ]
bearing = 233
loc = [ 51.281945, 6.745040 ]

[runways.EDDL.05L]
thr = [ 51.285295, 6.752085 ] 
bearing = 53
loc = [ 51.300616, 6.784241 ]

#-----------EDDK--------------

[runways.EDDK.31L]
thr = [ 50.858539, 7.138712 ]
bearing = 317

[runways.EDDK.13R]
thr = [ 50.870811, 7.120923 ] 
bearing = 137

[runways.EDDK.31R]
thr = [ 50.855240, 7.165640 ]
bearing = 317
loc = [ 50.884460, 7.123307 ]

[runways.EDDK.13L]
thr = [ 50.880434, 7.129133 ] 
bearing = 137
loc = [ 50.852869, 7.169062 ]

[runways.EDDK.24]
thr = [ 50.869653, 7.155208 ]
bearing = 244
loc = [ 50.858977, 7.120022 ]

[runways.EDDK.06]
thr = [ 50.860151, 7.123862 ] 
bearing = 64

#-----------EDDG--------------

[runways.EDDG.25]
thr = [ 52.137267, 7.697269 ]
bearing = 251
loc = [ 52.130467, 7.665046 ]

[runways.EDDG.07]
thr = [ 52.131519, 7.670055 ] 
bearing = 71
loc = [ 52.138294, 7.702111 ]

#-----------EDDR--------------

[runways.EDDR.27]
thr = [ 49.214936, 7.122372 ]
bearing = 268

[runways.EDDR.09]
thr = [ 49.214188, 7.097121 ] 
bearing = 88

#-----------EDLP--------------

[runways.EDLP.24]
thr = [ 51.619440, 8.629478 ]
bearing = 237

[runways.EDLP.06]
thr = [ 51.608713, 8.603167 ] 
bearing = 57

#-----------EDLW--------------

[runways.EDLW.24]
thr = [ 51.522206, 7.623252 ]
bearing = 241
loc = [ 51.513317, 7.598003 ]

[runways.EDLW.06]
thr = [ 51.516019, 7.605664 ] 
bearing = 61
loc = [ 51.524903, 7.630898 ]

#-----------EDLN--------------

[runways.EDLN.31]
thr = [ 51.226991, 6.511213 ]
bearing = 308

[runways.EDLN.13]
thr = [ 51.233725, 6.497791 ] 
bearing = 128

#-----------EDLV--------------

[runways.EDLV.27]
thr = [ 51.602069, 6.159739 ]
bearing = 272
loc = [ 51.602973, 6.118241 ]

[runways.EDLV.09]
thr = [ 51.602834, 6.124530 ] 
bearing = 92

#-----------EDFH--------------

[runways.EDFH.21]
thr = [ 49.957952, 7.273052 ]
bearing = 212
loc = [ 49.928704, 7.244244 ]

[runways.EDFH.03]
thr = [ 49.933671, 7.249122 ] 
bearing = 32
loc = [ 49.962504, 7.277585 ]

#-----------EDFM--------------

[runways.EDFM.27]
thr = [ 49.472512, 8.520011 ]
bearing = 273

[runways.EDFM.09]
thr = [ 49.472991, 8.506099 ] 
bearing = 93

#-----------EDSB--------------

[runways.EDSB.21]
thr = [ 48.788850, 8.089408 ]
bearing = 212
loc = [ 48.766042, 8.068028 ]

[runways.EDSB.03]
thr = [ 48.769861, 8.071612 ] 
bearing = 32
loc = [ 48.792711, 8.093026 ]

#-----------EDTL--------------

[runways.EDTL.21]
thr = [ 48.381150, 7.837373 ]
bearing = 208
loc = [ 48.355481, 7.816612 ]

[runways.EDTL.03]
thr = [ 48.357353, 7.818134 ] 
bearing = 28