[data]

#[data.rawdata]
#type = "raw"
#source = "data"

#[data.eddl]
#type = "aixm"
#source = "aixm/EDDL_AerodromeMapping_2024-06-13_2024-06-13_snapshot.xml"
#
#[data.eddl_layout]
#type = "kml"
#source = "kml/EDDL/layout.kml"
#
#[data.eddg_layout]
#type = "kml"
#source = "kml/EDDG/layout.kml"
#
[data.edlp]
type = "aixm"
source = "aixm/EDLP_AerodromeMapping_2024-05-16_2024-05-16_snapshot.xml"

[data.edlp_layout]
type = "kml"
source = "kml/EDLP/layout.kml"
#
#[data.edlw]
#type = "aixm"
#source = "aixm/EDLW_AerodromeMapping_2024-05-16_2024-05-16_snapshot.xml"
#
#[data.edlw_layout]
#type = "kml"
#source = "kml/EDLW/layout.kml"
#
#[data.edln]
#type = "aixm"
#source = "aixm/EDLN_AerodromeMapping_2024-06-13_2024-06-13_snapshot.xml"
#
#[data.edln_layout]
#type = "kml"
#source = "kml/EDLN/layout.kml"
#
#[data.edlv]
#type = "aixm"
#source = "aixm/EDLV_AerodromeMapping_2024-06-13_2024-06-13_snapshot.xml"
#
#[data.edlv_layout]
#type = "kml"
#source = "kml/EDLV/layout.kml"



[profiles]

[profiles.Default]
maps = [
#    { map = "EDDL", target = "grp/eddl.txt" },
#    { map = "EDDG", target = "grp/eddg.txt" },
    { map = "EDLP", target = "grp/edlp.txt" },
#    { map = "EDLW", target = "grp/edlw.txt" },
#    { map = "EDLN", target = "grp/edln.txt" },
#    { map = "EDLV", target = "grp/edlv.txt" }
]
dir = "grp"
aliases = [ "Default" ]

#[profiles.TWR_DAY]
#maps = [
#    { map = "settings-grplugin-phoenix", target = "Plugins/EDWW FIR beta/TWR_DAY/GRpluginSettings.txt" },
#    { map = "settings-topsky-phoenix", target = "Plugins/EDWW FIR beta/TWR_DAY/TopSkySettings.txt" },
#    { map = "grplugin-phoenix", target = "Plugins/EDWW FIR beta/TWR_DAY/GRpluginMaps.txt" },
#    { map = "topsky-phoenix", target = "Plugins/EDWW FIR beta/TWR_DAY/TopSkyMaps.txt" },
#]
#dir = "Plugins/EDWW FIR beta/TWR_DAY/"
#aliases = [ "bright" ]

[runways]

#-----------EDDL--------------

[runways.EDDL.23L]
thr = [ 51.294278, 6.782787 ]
bearing = 233
loc = [ 51.277864, 6.748345 ]

[runways.EDDL.05R]
thr = [ 51.281248, 6.755424 ] 
bearing = 53
loc = [ 51.297669, 6.789874 ]

[runways.EDDL.23R]
thr = [ 51.296757, 6.776128 ]
bearing = 233
loc = [ 51.281945, 6.745040 ]

[runways.EDDL.05L]
thr = [ 51.285295, 6.752085 ] 
bearing = 53
loc = [ 51.300616, 6.784241 ]

#-----------EDDG--------------

[runways.EDDG.25]
thr = [ 52.137267, 7.697269 ]
bearing = 251
loc = [ 52.130467, 7.665046 ]

[runways.EDDG.07]
thr = [ 52.131519, 7.670055 ] 
bearing = 71
loc = [ 52.138294, 7.702111 ]

#-----------EDLP--------------

[runways.EDLP.24]
thr = [ 51.619440, 8.629478 ]
bearing = 237

[runways.EDLP.06]
thr = [ 51.608713, 8.603167 ] 
bearing = 57

#-----------EDLW--------------

[runways.EDLW.24]
thr = [ 51.522206, 7.623252 ]
bearing = 241
loc = [ 51.513317, 7.598003 ]

[runways.EDLW.06]
thr = [ 51.516019, 7.605664 ] 
bearing = 61
loc = [ 51.524903, 7.630898 ]

#-----------EDLN--------------

[runways.EDLN.31]
thr = [ 51.226991, 6.511213 ]
bearing = 308

[runways.EDLN.13]
thr = [ 51.233725, 6.497791 ] 
bearing = 128

#-----------EDLV--------------

[runways.EDLV.27]
thr = [ 51.602069, 6.159739 ]
bearing = 272
loc = [ 51.602973, 6.118241 ]

[runways.EDLV.09]
thr = [ 51.602834, 6.124530 ] 
bearing = 92

